# Generated by Django 2.1 on 2018-10-28 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20181028_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='anguage',
            new_name='language',
        ),
    ]
