# Generated by Django 2.1 on 2018-11-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_catalo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessorVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('watched_as_ad', models.IntegerField()),
                ('watched_as_video', models.IntegerField()),
            ],
            options={
                'db_table': 'processor_videos',
                'managed': False,
            },
        ),
    ]
