# Generated by Django 2.1 on 2018-11-02 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_customvideogroup_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.CustomVideoGroup')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ProcessorVideo')),
            ],
        ),
    ]
