# Generated by Django 2.1 on 2018-11-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20181102_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupvideo',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupvideo',
            name='video',
        ),
        migrations.AddField(
            model_name='customvideogroup',
            name='videos',
            field=models.ManyToManyField(help_text='Select videos to be added to this custom group', to='catalog.ProcessorVideo'),
        ),
        migrations.DeleteModel(
            name='GroupVideo',
        ),
    ]
